version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    environment:
      # Эти переменные можно переопределить через .env
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"