version: '3.9'

services:
  backend:
    build: .
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - "5000:5000"
    networks:
      - default

networks:
  default:
    driver: bridge